version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - gocritic
    - gocognit
    - gocyclo
    - maintidx
    - dupl
    - mnd
    - unparam
    - ireturn
    - goconst
    - errcheck
  settings:
    goconst:
      ignore-tests: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
          - dupl
          - mnd
          - unparam
      - path: cmd/
        linters:
          - errcheck
